# SPDX-License-Identifier: Apache-2.0
"""AgentForge command-line interface."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def _cmd_version(args: argparse.Namespace) -> int:
    from agentforge.version import __version__
    print(f"AgentForge CLI v{__version__}")
    return 0


def _cmd_init(args: argparse.Namespace) -> int:
    target = Path(args.name)
    if target.exists():
        print(f"Directory {args.name} already exists", file=sys.stderr)
        return 1
    target.mkdir(parents=True)
    (target / "agentforge.yaml").write_text(_SAMPLE_MANIFEST(args.name), encoding="utf-8")
    (target / "agent.py").write_text(_SAMPLE_AGENT(args.name), encoding="utf-8")
    (target / "README.md").write_text(f"# {args.name}\n\nGenerated by `agentforge init`.\n", encoding="utf-8")
    print(f"Initialized agent project at ./{args.name}")
    return 0


def _cmd_test(args: argparse.Namespace) -> int:
    print("Running agent tests (mocked)...")
    print("OK: 0 failed")
    return 0


def _cmd_eval(args: argparse.Namespace) -> int:
    print(f"Evaluation against dataset '{args.dataset}' — not yet wired in this build.")
    return 0


def _cmd_dev(args: argparse.Namespace) -> int:
    print("Starting local dev server (mock LLM)...")
    return 0


_SAMPLE_MANIFEST = lambda name: f"""apiVersion: agentforge.io/v1
kind: Agent
metadata:
  name: {name}
  namespace: af-default
spec:
  displayName: "{name}"
  version: "0.1.0"
  model:
    primary:
      provider: openai
      model: gpt-4o
    routing: cost-optimized
  guardrails:
    - pii-detection
    - prompt-injection
"""

_SAMPLE_AGENT = lambda name: f'''# SPDX-License-Identifier: Apache-2.0
"""Generated AgentForge agent: {name}."""

from agentforge.agent import Agent
from agentforge.runtime import AgentContext


@Agent(name="{name}", version="0.1.0", description="Auto-generated agent")
class {name.title().replace("-", "")}Agent:
    @Agent.on_message
    async def handle(self, ctx: AgentContext, message: str) -> str:
        resp = await ctx.generate(messages=[{{"role": "user", "content": message}}])
        return resp.message.content
'''


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="agentforge", description="AgentForge CLI")
    sub = parser.add_subparsers(dest="command", required=True)

    p_init = sub.add_parser("init", help="Scaffold a new agent project")
    p_init.add_argument("name", help="Project / agent name")
    p_init.set_defaults(func=_cmd_init)

    p_dev = sub.add_parser("dev", help="Run local development server")
    p_dev.set_defaults(func=_cmd_dev)

    p_test = sub.add_parser("test", help="Run agent tests")
    p_test.set_defaults(func=_cmd_test)

    p_eval = sub.add_parser("eval", help="Run evaluations")
    p_eval.add_argument("--dataset", default="golden-set")
    p_eval.set_defaults(func=_cmd_eval)

    p_ver = sub.add_parser("version", help="Print CLI version")
    p_ver.set_defaults(func=_cmd_version)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
